### ISSUE TITLE
[Crag] Hover popup flows outside of main container.

### ISSUE THREAD

**Issue by salamca** [plezanje-net/web#100]
![image](https://user-images.githubusercontent.com/10534304/145470795-601e0973-4a89-445d-9605-467c43d16b3c.png)

**Comment by NejcS** [comment]
Remove the popups, make the route rows expendable when clicked.

If expanded it should show a preview of ascents and comments. If user clicks on "see more" it should lead him to the route page just like clicking on the route name should.

Also fix https://github.com/plezanje-net/web/issues/90 while you are at it.
