### ISSUE TITLE
[Log] Fix cache. Newly logged routes not reflected on crag route list.

### ISSUE THREAD

**Issue by salamca** [plezanje-net/web#143]
Go to a crag and log a route that you have not logged before.
Without refreshing navigate back to the crag. See that there is no icon next to the route that you just logged.

**Comment by salamca** [comment]
This was temporarily resolved by clearing the cache after every mutation. Should optimise this solution.

**Comment by demshy** [comment]
https://github.com/plezanje-net/web/issues/208
