### ISSUE TITLE
[Error handling] Global / component error handling

### ISSUE THREAD

**Issue by demshy** [plezanje-net/web#148]
Handle network errors on a global level (using apollo onError listener in graphql module). We could maybe show a certain error layour for these errors.

The local (component) error handler can then ignore network errors and focus on graphql ones. We can create a generic error handler wrapper that will also ignore token_expired error and treat such request as still loading (until the logout promise is resolved and the user is redirected).

**Comment by salamca** [comment]
outdated issue.
closing...
