### ISSUE TITLE
[SEO] Run lighthouse and go through the estimated improvements and make tickets

### ISSUE THREAD

**Issue by NejcS** [plezanje-net/web#247]
Run lighthouse in dev tools, find the weak points and create separate tasls if the suggested improvements are possible to achieve.

**Comment by demshy** [comment]
Enable text compression ✅ 
(added gzip to nginx config)

**Comment by demshy** [comment]
Use HTTP/2 ✅

**Comment by demshy** [comment]
![Screenshot 2022-03-14 at 19 16 20](https://user-images.githubusercontent.com/19568230/158235544-7156b728-d994-42a1-bfcd-2f92f914fbec.png)
