### ISSUE TITLE
[Log, Clubs] Date range picker manual input fails

### ISSUE THREAD

**Issue by salamca** [plezanje-net/web#312]
Try entering the range manually. 
Se that when you enter the first number the start date is completed and you can never enter the whole start date...

**Comment by ipspace** [comment]
+1

The start date manual entry does not recognize leading zeroes or 4-digit years -- I was able to enter 1.1.21 but not 01.01.2021. 

I was also not able to enter the end date.

**Comment by demshy** [comment]
This will solved by elegantly disabling user input (only on date ranges, not single dates) for now.

All we need to do is add readonly property on the input, I think.
