### ISSUE TITLE
[Route] Some routes have difficulty displayed at the top other at the bottom. Grade should always be first. See scrshts for examples from Ter.

### ISSUE THREAD

**Issue by salamca** [plezanje-net/web#361]
![image](https://user-images.githubusercontent.com/10534304/168283736-884df1fc-7146-4158-b9b9-acd43729bdec.png)

![image](https://user-images.githubusercontent.com/10534304/168287446-ea5f7a6f-0a28-49fe-ada3-920917705984.png)

**Comment by demshy** [comment]
done with queries straight to production
the problem was that grades were added as extGrade to 400+ sport routes
