### ISSUE TITLE
[HomePage] Design for landing page

### ISSUE THREAD

**Issue by MaticDiba** [plezanje-net/web#6]
We need to define what should be displayed on homepage and where.

One suggestion was:
- Search bar for simple search.  Results can be grouped by entity type (crags, routes, ...) see #7 
- ...

Wireframe would be helpful.

**Comment by NejcS** [comment]
Maybe last ascents would be useful (helps to see if a certain crag is already dry) or "this week's most popular crag" so you know where you shouldn't go :)

**Comment by salamca** [comment]
partly done. moved to backlog.
